name: Use GitHub Secret

on: 
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Secret in a Script
        env:
          MY_SECRET: ${{ secrets.GPT_SECRET }}
        run: echo "Secret is being used but not printed."
